# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Chen Hao
tagline:             Keep Simple Heart
url:                 http://haoeric.com
paginate:            1
baseurl:             ""

pages_list:       
  About: '/about'
  Posts: '/archive'
  Blog Categories: '/category'
  Feed: '/atom.xml'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Chen Hao
  url:               http://haoeric.com
  email:             haoeric@hotmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/haoeric/haoeric.github.io
