# Permalinks, just title to tidy up the page url
permalink: /:title/

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes

collections:
  posts:
    output: true

# Setup
title: Hao Chen | 陈浩
tagline: focus and diffuse
email: haoeric@hotmail.com
description: >
  Bioinformatician, Data Enthusiast, Certified AWS Solution Architect, Top Ranking R Packages Developer 
url: http://haoeric.com
paginate: 1
baseurl: ""
markdown: kramdown
encoding: "utf-8"
github_username:  haoeric

pages_list:       
  Posts: '/posts'
  About Me: '/readme'

# Using Rouge with Jekyll
# https://sacha.me/articles/jekyll-rouge/
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

  
# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: compressed

# About/contact
author:
  name: Chen Hao
  url: http://haoeric.com
  email: haoeric@hotmail.com

# Custom vars
version: 1.0.0
github: 
  repo: https://github.com/haoeric/haoeric.github.io
